version: '3.9'

services:
  runtime:
    container_name: client
    build:
      dockerfile: docker/Dockerfile
      context: .
    tty: true
    networks:
      - prod

networks:
  prod:
    name: production_network
    external: true